# Generated by Django 3.2 on 2021-05-29 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='specs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
